tlsTermination:
  foo-domain:
    domain: foo.test.example.com
    targetIPs:
    - 10.10.10.1
    - 10.10.10.2
    targetPort: 9000
    secret: foo-secret
  bar-domain:
    domain: bar.test.example.com
    paths:
      - path: /
        targetIPs:
        - 10.10.10.2
        - 10.10.10.2
        targetPort: 9001
      - path: /api
        targetIPs:
        - 10.10.10.2
        - 10.10.10.2
        targetPort: 9002
      - path: /foo
        targetIPs:
        - 10.10.10.6
        - 10.10.10.7
        targetPort: 9003
