tlsTermination:
  foo-domain:
    domain: foo.test.example.com
    targetIPs:
    - 10.10.10.1
    - 10.10.10.2
    targetPort: 9000
    secret: foo-secret
  bar-domain:
    domain: bar.test.example.com
    targetIPs:
    - 10.10.10.2
    - 10.10.10.2
    targetPort: 9001
