apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-service
spec:
  type: NodePort
  selector:
    app: acme-challenge-dispatcher
  ports:
    - name: challenges
      protocol: TCP
      port: 8089
      nodePort: 30950
