apiVersion: v1
kind: Pod
metadata:
  name: acme-challenge-dispatcher
  labels:
    app: acme-challenge-dispatcher
spec:
  containers:
  - name: acme-challenge-dispatcher
    image: localhost/acme-challange-dispatcher:v8
    imagePullPolicy: IfNotPresent
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: LABEL_SELECTOR
      value: app=acme-http-solver
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
  restartPolicy: Always
  automountServiceAccountToken: true
  serviceAccountName: acme-challenge-dispatcher
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    seccompProfile:
      type: RuntimeDefault