apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-dispatcher-service
spec:
  type: NodePort
  selector:
    app: acme-challenge-dispatcher
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080