apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: acme-challenge-dispatcher-pod-monitor
spec:
  selector:
    matchLabels:
      app: acme-challenge-dispatcher
  podMetricsEndpoints:
  - port: healthz
    path: /metrics
    interval: 10s