apiVersion: v1
kind: Pod
metadata:
  name: acme-http-solver
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - --listen-port=8089
    - --domain=example.com
    - --token=abc
    - --key=def
    image: quay.io/jetstack/cert-manager-acmesolver:v1.14.3
    imagePullPolicy: IfNotPresent
    name: acmesolver
    ports:
    - containerPort: 8089
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  restartPolicy: OnFailure
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: default
  terminationGracePeriodSeconds: 30

