apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-challenge-dispatcher
  namespace: acme-challenge-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acme-challenge-dispatcher
  namespace: acme-challenge-test
rules:
- apiGroups: [""]
  resources: ["endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acme-challenge-dispatcher
  namespace: acme-challenge-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acme-challenge-dispatcher
subjects:
- kind: ServiceAccount
  name: acme-challenge-dispatcher
  namespace: acme-challenge-test