kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: fair-share-cluster
networking:
  podSubnet: "10.122.0.0/16"
  serviceSubnet: "10.46.0.0/12"
nodes:
- role: control-plane
- role: worker
  labels:
    class: critical
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: critical-workload-node
      kubeletExtraArgs:
        system-reserved: "cpu=10,memory=2Gi"
        kube-reserved: "cpu=8,memory=2Gi"

