apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: prometheus-server
        persistentVolumeClaim:
          claimName: prometheus-server
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
        - name: prometheus-server
          mountPath: /var/www
