apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trivy

configMapGenerator:
  - name: trivy-additional-values
    files:
      - values.yaml=trivy-additional-values.yaml
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: trivy-additional-secrets
    files:
      - values.yaml=trivy-additional-secrets.yaml
    options:
      disableNameSuffixHash: true

#  - name: trivy-additional-values-2
#    envs:
#    - .env
#    options:
#      disableNameSuffixHash: true
#  - name: echo-additional-values
#    files:
#      - values.yaml=echo-additional-values.yaml
#    options:
#      disableNameSuffixHash: true