apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: httpd-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: httpd-metrics-exporter
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 10s
