kind: Pod
apiVersion: v1
metadata:
  name: sysctlpod
spec:
  containers:
  - image: busybox:latest
    command: [ "sleep"]
    args: ["infinity"]
    name: my-pod
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]
    securityContext:
      seLinuxOptions:
        type: "container_engine_X"
        role: my_role
        user: root
      seccompProfile:
        type: RuntimeDefault
  securityContext:
    sysctls:
    - name: kernel.shm_rmid_forced
      value: "0"
    - name: net.core.somaxconn
      value: "1024"
    - name: kernel.msgmax
      value: "65536"
    seLinuxOptions:
      type: "container_engine_X"
      role: my_role
      user: root
    seccompProfile:
      type: Unconfined