apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: ingress-test-1
spec:
  ingressClassName: nginx
  rules:
  - host: ingress-test-1.example.com
    http:
      paths:
      - backend:
          service:
            name: ingress-test
            port:
              number: 8080
        path: /
        pathType: Prefix
