apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ingress-test.fullname" . }}
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ingress-test.fullname" . }}
  policyTypes:
  - Egress
  - Ingress
