apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-test.fullname" . }}
  labels:
    {{- include "ingress-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    {{- include "ingress-test.selectorLabels" . | nindent 4 }}

{{- $root := . -}}
{{ range $podIndex := until (.Values.replicaCount | int) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-test.fullname" $root }}-{{ $podIndex }}
  labels:
    {{- include "ingress-test.labels" $root | nindent 4 }}-{{ $podIndex }}
spec:
  type: {{ $root.Values.service.type }}
  clusterIP: None
  ports:
  {{- range $root.Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: ingress-test-{{ $podIndex }}
{{ end -}}
