apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-test.fullname" . }}
  labels:
    {{- include "ingress-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    {{- include "ingress-test.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-test.fullname" . }}-0
  labels:
    {{- include "ingress-test.labels" . | nindent 4 }}-0
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: ingress-test-0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-test.fullname" . }}-1
  labels:
    {{- include "ingress-test.labels" . | nindent 4 }}-0
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: ingress-test-1
