kind: Service
apiVersion: v1
metadata:
  name: httpd
  namespace: httpd-autoscaling
  labels:
    app.kubernetes.io/name: httpd
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: httpd
  selector:
    app.kubernetes.io/name: httpd
  type: ClusterIP