apiVersion: v1
kind: Service
metadata:
  name: httpd-metrics-exporter
  namespace: httpd-autoscaling
  labels:
    app.kubernetes.io/name: httpd-metrics-exporter
spec:
  ports:
    - port: 9117
      targetPort: 9117
      name: prometheus
  selector:
    app.kubernetes.io/name: httpd
  type: ClusterIP