apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: httpd-scaled-object
  namespace: httpd-autoscaling
  labels:
    deploymentName: httpd
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  minReplicaCount: 1
  maxReplicaCount: 5
  scaleTargetRef:
    name: httpd
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090
        query: sum(rate(apache_accesses_total[60s]))/sum(kube_pod_info{pod=~"httpd.*"})
        unsafeSsl: "true"
        threshold: '100'
        activationThreshold: '100'
