apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: httpd-autoscaling
  labels:
    app.kubernetes.io/name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: httpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports:
            - containerPort: 8888
              name: httpd
          volumeMounts:
            - mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
              name: httpd
        - name: httpd-exporter
          image: lusotycoon/apache-exporter:v1.0.0
          ports:
            - containerPort: 9117
              name: prometheus
          command: [ "/bin/apache_exporter" ]
          args: [ "--scrape_uri=http://localhost:8888/server-status?auto", "--web.listen-address=:9117", "--telemetry.endpoint=/metrics" ,"--log.level=debug"]
      volumes:
        - name: httpd
          configMap:
            name: httpd
            items:
              - key: httpd.conf
                path: httpd.conf