{{- range $node, $value := .Values.tlsTermination }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $node }}
  labels:
    {{- include "tls-termination.labels" $ | nindent 4 }}
spec:
  tls:
  - hosts:
    - {{ $value.domain }}
    secretName: {{ if $value.secret }}{{ $value.secret }}{{ else }}{{ printf "%s-secret" $node }}{{ end }}
  rules:
  - host: {{ $value.domain }}
    http:
      paths:
      {{- range $i, $path := $value.paths }}
      - pathType: Prefix
        path: "{{ $path.path }}"
        backend:
          service:
            name: {{ printf "%s-%d" $node $i }}
            port:
              number: {{ $path.targetPort }}
      {{- end }}
{{- range $i, $path := $value.paths }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%d" $node $i }}
  labels:
    {{- include "tls-termination.labels" $ | nindent 4 }}
spec:
  ports:
  - port: {{ $path.targetPort }}
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ printf "%s-%d" $node $i }}
  labels:
    {{- include "tls-termination.labels" $ | nindent 4 }}
subsets:
- addresses:
  {{- range $path.targetIPs }}
  - ip: {{ . }}
  {{- end }}
  ports:
  - port: {{ $path.targetPort }}
{{- end }}
{{- end }}