{{- range $node, $value := .Values.tlsTermination }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $node }}
  labels:
    {{- include "tls-termination.labels" $ | nindent 4 }}
spec:
  tls:
  - hosts:
    - {{ $value.domain }}
    secretName: {{ if $value.secret }}{{ $value.secret }}{{ else }}{{ printf "%s-secret" $node }}{{ end }}
  rules:
  - host: {{ $value.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $node }}
            port:
              number: {{ $value.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $node }}
  labels:
    {{- include "tls-termination.labels" $ | nindent 4 }}
spec:
  ports:
  - port: {{ $value.port }}
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ $node }}
  labels:
    {{- include "tls-termination.labels" $ | nindent 4 }}
subsets:
- addresses:
  {{- range $value.targetIPs }}
  - ip: {{ . }}
  {{- end }}
  ports:
  - port: {{ $value.port }}
{{- end }}