apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"name":"httpd-service-monitor","namespace":"monitoring"},"spec":{"endpoints":[{"interval":"10s","path":"/metrics","port":"prometheus"}],"namespaceSelector":{"matchNames":["httpd-autoscaling"]},"selector":{"matchLabels":{"app.kubernetes.io/name":"httpd-metrics-exporter"}}}}
  creationTimestamp: "2024-08-31T12:56:52Z"
  generation: 1
  name: httpd-service-monitor
  namespace: monitoring
  resourceVersion: "24075"
  uid: 84b3dfd5-435e-4463-95d4-af1daaa172d8
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: prometheus
  namespaceSelector:
    matchNames:
    - httpd-autoscaling
  selector:
    matchLabels:
      app.kubernetes.io/name: httpd-metrics-exporter
