apiVersion: v1
kind: ConfigMap
metadata:
  name: load-test-config
  namespace: httpd-autoscaling
data:
    load-test.js: |
      import http from 'k6/http';
      import { sleep } from 'k6';
      
      export const options = {
          stages: [
              {
                  duration: '30s',
                  target: 100
              },
              {
                  duration: '30s',
                  target: 200
              },
              {
                  duration: '30s',
                  target: 300
              },
              {
                  duration: '30s',
                  target: 300
              },
              {
                  duration: '10s',
                  target: 0
              }
          ]
      }
      
      export default function () {
          http.get('http://httpd.httpd-autoscaling.svc.cluster.local:8888');
          sleep(1);
      }