apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 4 # by default is 1
  minReadySeconds: 0 # by default is 0
  updateStrategy:
    type: RollingUpdate # RollingUpdate is the default value
  podManagementPolicy: Parallel # OrderedReady can prevent the stateful set to rollback into a working state
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.9
        ports:
        - containerPort: 80
          name: web
        readinessProbe:
            httpGet:
                path: /index.html
                port: web
            initialDelaySeconds: 5
        livenessProbe:
            httpGet:
                path: /index.html
                port: web
            initialDelaySeconds: 5
        startupProbe:
            httpGet:
                path: /index.html
                port: web
            initialDelaySeconds: 5