global:
  baseValue: "from-base-value"
  overriddenValue: "from-base-value"

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.27.2"

numberOfConfigMaps: 20

deploymentAnnotations:
  reloader.stakater.com/auto: "true"
  reloader.stakater.com/delayed-upgrade: "10s"
