apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaling-test-rolebinding
  namespace: httpd-autoscaling
subjects:
- kind: ServiceAccount
  name: scaling-test-sa
  namespace: httpd-autoscaling
roleRef:
  kind: Role
  name: scaling-test-role
  apiGroup: rbac.authorization.k8s.io