apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /tmp/prometheus
