services:
  client:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: client
    hostname: client
    command: sleep infinity
    networks:
      frontend-network:
        ipv4_address: 192.168.1.2
  frontend:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: frontend
    hostname: frontend
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      frontend-network:
        ipv4_address: 192.168.1.1
      backend-network:
        ipv4_address: 10.0.0.1

  backend:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: backend
    hostname: backend
    command: nc -l -u -k -p 1234
    networks:
      backend-network:
        ipv4_address: 10.0.0.2

  backend2:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: backend2
    hostname: backend2
    command: nc -l -t -k -p 1234
    networks:
      backend-network:
        ipv4_address: 10.0.0.3

networks:
  frontend-network:
    driver: bridge
    name: frontend-net
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.5

  backend-network:
    driver: bridge
    name: backend-net
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.5
