services:
  client:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: client
    hostname: client
    command: sleep infinity
    networks:
      frontend-network:
        ipv4_address: 192.168.1.2
  frontend:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: frontend
    hostname: frontend
    command: >
      sh -c "
      echo 1 > /proc/sys/net/ipv4/ip_forward &&
      iptables -A PREROUTING -t nat -p udp -d 192.168.1.1 --dport 27017 -j DNAT --to-destination 10.0.0.2:1234 &&
      iptables -A PREROUTING -t nat -p tcp -d 192.168.1.1 --dport 27018 -j DNAT --to-destination 10.0.0.2:5678 &&
      iptables -A POSTROUTING -t nat -p tcp -d 10.0.0.2 --dport 5678 -j SNAT --to-source 10.0.0.1 &&
      iptables -t nat -A PREROUTING -p udp --dport 27019 -m statistic --mode nth --every 3 --packet 0 -j DNAT --to-destination 10.0.0.2:1234 &&
      iptables -t nat -A PREROUTING -p udp --dport 27019 -m statistic --mode nth --every 2 --packet 0 -j DNAT --to-destination 10.0.0.3:1234 &&
      iptables -t nat -A PREROUTING -p udp --dport 27019 -j DNAT --to-destination 10.0.0.4:1234 &&
      iptables -t nat -A PREROUTING -p tcp --dport 27020 -m statistic --mode nth --every 3 --packet 0 -j DNAT --to-destination 10.0.0.2:5678 &&
      iptables -t nat -A PREROUTING -p tcp --dport 27020 -m statistic --mode nth --every 2 --packet 0 -j DNAT --to-destination 10.0.0.3:5678 &&
      iptables -t nat -A PREROUTING -p tcp --dport 27020 -j DNAT --to-destination 10.0.0.4:5678 &&
      iptables -A POSTROUTING -t nat -p tcp -d 10.0.0.3 --dport 5678 -j SNAT --to-source 10.0.0.1 &&
      iptables -A POSTROUTING -t nat -p tcp -d 10.0.0.4 --dport 5678 -j SNAT --to-source 10.0.0.1 &&
      sleep infinity
      "
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      frontend-network:
        ipv4_address: 192.168.1.1
      backend-network:
        ipv4_address: 10.0.0.1

  backend:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: backend
    hostname: backend
    command: sh -c "nc -l -u -k -p 1234 & nc -l -t -k -p 5678 & wait"
    networks:
      backend-network:
        ipv4_address: 10.0.0.2

  backend2:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: backend2
    hostname: backend2
    command: sh -c "nc -l -u -k -p 1234 & nc -l -t -k -p 5678 & wait"
    networks:
      backend-network:
        ipv4_address: 10.0.0.3

  backend3:
    image: ghcr.io/cicdior/alpine-iptables:1.0.0@sha256:70d77b55a681800b975ec0e7c0e0d3bc6646a94b52f93b243d63ceca2eb9e0fc
    container_name: backend3
    hostname: backend3
    command: sh -c "nc -l -u -k -p 1234 & nc -l -t -k -p 5678 & wait"
    networks:
      backend-network:
        ipv4_address: 10.0.0.4

networks:
  frontend-network:
    driver: bridge
    name: frontend-net
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.5

  backend-network:
    driver: bridge
    name: backend-net
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.10
