prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels:
        prometheus-monitoring: "enabled"
    serviceMonitorNamespaceSelector:
      matchLabels:
        prometheus-monitoring: "enabled"