apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coffee
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: coffee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tea
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: tea
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secure-coffee-config
data:
  nginx.conf: |
    events {}
    
    http {
        server {
            listen 80;
            location / {
                return 200 'Hello from Secure Coffee (HTTP)!\n';
                add_header Content-Type text/plain;
            }
        }
        
        server {
            listen 443 ssl;
            ssl_certificate /etc/ssl/certs/tls.crt;
            ssl_certificate_key /etc/ssl/private/tls.key;
            
            location / {
                return 200 'Hello from Secure Coffee (HTTPS)!\n';
                add_header Content-Type text/plain;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-coffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-coffee
  template:
    metadata:
      labels:
        app: secure-coffee
    spec:
      containers:
      - name: secure-coffee
        image: nginx:1.25
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: ssl-private
          mountPath: /etc/ssl/private
          readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: secure-coffee-config
        - name: ssl-certs
          secret:
            secretName: internal-cafe-secret
            items:
            - key: tls.crt
              path: tls.crt
        - name: ssl-private
          secret:
            secretName: internal-cafe-secret
            items:
            - key: tls.key
              path: tls.key
---
apiVersion: v1
kind: Service
metadata:
  name: secure-coffee
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: secure-coffee