apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
data:
  index.html: |
    <html>
    <body>
      <h1>Hello, World!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: apache-httpd
spec:
  securityContext:
    fsGroup: 3000
    runAsGroup: 10000
    runAsUser: 10003
    seccompProfile:
      type: RuntimeDefault
  automountServiceAccountToken: false
  shareProcessNamespace: true
  containers:
  - name: main
    image: httpd:2.4
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
        - CAP_NET_RAW
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    volumeMounts:
    - name: html-content
      mountPath: /usr/local/apache2/htdocs/
      subPath: index.html
  - name: sidecar
    image: busybox
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
        - CAP_NET_RAW
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    command: ["/bin/sh", "-c", "while true; do inotifywait -e modify /config/index.html && kill -s SIGUSR1 1; done"]
    volumeMounts:
    - name: html-content
      mountPath: /config
  volumes:
  - name: html-content
    configMap:
      name: html-content