kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    mode: ipvs
    logging:
      verbosity: 9
    ipvs:
      scheduler: "rr"  # Round Robin scheduler.
      syncPeriod: 6s
- role: worker
